name: Build Unsigned iOS App
on: 
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Setup Rust (For Bloomee Core)
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-ios, x86_64-apple-ios

      - name: Upgrade Packages & Fix iOS Platform
        run: |
          flutter clean
          # Принудительно обновляем все плагины, чтобы получить версию share_handler без багов
          flutter pub upgrade
          flutter pub get
          
          cd ios
          # Сносим старые блокировки подов
          rm -rf Podfile.lock Pods
          
          # Удаляем любые старые упоминания платформы в Podfile
          sed -i '' '/platform :ios/d' Podfile
          
          # Железобетонно прописываем iOS 14.0 в самую первую строку файла
          echo "platform :ios, '14.0'" | cat - Podfile > temp_podfile
          mv temp_podfile Podfile

      - name: Update CocoaPods (Safe Mode)
        run: pod repo update

      - name: Build iOS (No Codesign)
        # Flutter сам создаст нужные симлинки и соберет проект
        run: flutter build ios --release --no-codesign

      - name: Package to IPA
        run: |
          mkdir Payload
          mv build/ios/iphoneos/Runner.app Payload/
          zip -qr BloomeeTunes.ipa Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BloomeeTunes-IPA
          path: BloomeeTunes.ipa
