name: Build Unsigned iOS App
on: 
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Clean and Get Packages
        run: |
          flutter clean
          flutter pub get

      - name: Fix iOS Platform Version
        working-directory: ios
        # Находим закомментированную строку платформы и жестко прописываем iOS 14.0
        run: |
          sed -i '' "s/# platform :ios.*/platform :ios, '14.0'/g" Podfile

      - name: Update CocoaPods Repo
        working-directory: ios
        # Обновляем индексы репозиториев, но НЕ запускаем pod install руками
        run: pod repo update

      - name: Build iOS (No Codesign)
        # Эта команда сама создаст нужные симлинки для share_handler и скачает поды в правильный момент
        run: flutter build ios --release --no-codesign

      - name: Package to IPA
        run: |
          mkdir Payload
          mv build/ios/iphoneos/Runner.app Payload/
          zip -qr BloomeeTunes.ipa Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BloomeeTunes-IPA
          path: BloomeeTunes.ipa
