name: Build Unsigned iOS App
on: 
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Setup Rust (For Bloomee Core)
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-ios, x86_64-apple-ios

      # === ВАЖНО: ТА САМАЯ СЕРЕБРЯНАЯ ПУЛЯ ===
      # Отключаем новый SwiftPM, чтобы он не ломал CocoaPods внутри share_handler
      - name: Disable SwiftPM 
        run: flutter config --no-enable-swift-package-manager

      - name: Prepare Flutter Packages
        run: |
          flutter clean
          flutter pub get

      - name: Fix iOS Platform Version
        working-directory: ios
        run: |
          rm -rf Podfile.lock Pods
          sed -i '' '/platform :ios/d' Podfile
          echo "platform :ios, '14.0'" | cat - Podfile > temp_podfile
          mv temp_podfile Podfile

      - name: Build iOS (No Codesign)
        # Flutter сам скачает поды, и теперь, без SwiftPM, он корректно увидит share_handler_ios_models
        run: flutter build ios --release --no-codesign

      - name: Package to IPA
        run: |
          mkdir Payload
          mv build/ios/iphoneos/Runner.app Payload/
          zip -qr BloomeeTunes.ipa Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BloomeeTunes-IPA
          path: BloomeeTunes.ipa
